### ISSUE TITLE
AngularJS error when adding city name

### ISSUE THREAD

**Issue by spacorum** [nextcloud/weather#33]
I´m getting an error on file /apps/weather/js/angular/angular.min.js when I try to add a new city:

`angular.min.js?v=a4c3b07…:107 TypeError: $http.post(...).success(...).error(...).fail is not a function
    at b.$scope.addCity (app.js?v=a4c3b07…:266)
    at fn (eval at compile (angular.min.js?v=a4c3b07…:212), <anonymous>:4:305)
    at f (angular.min.js?v=a4c3b07…:253)
    at b.$eval (angular.min.js?v=a4c3b07…:133)
    at b.$apply (angular.min.js?v=a4c3b07…:133)
    at HTMLInputElement.<anonymous> (angular.min.js?v=a4c3b07…:254)
    at HTMLInputElement.dispatch (jquery.min.js?v=a4c3b07…:3)
    at HTMLInputElement.r.handle (jquery.min.js?v=a4c3b07…:3)`

`POST https://xxxxxx/apps/weather/city/add 404 (Not Found)`

I´m using NextCloud VM version (Nextcloud_Community_VM_PRODUCTION). I tried to add the city anyway but is not possible, the error seems to block the form action.

Any ideas? Thanks in advance.

**Comment by nerzhul** [comment]
404 not found mean the remote city is not found on OWM can you check on openweathermap.org ?

**Comment by spacorum** [comment]
I´m afraid that´s not the problem. The city appears perfectly in openweathermap. This is a JS error, I guess that even before the AJAX call that brings the cities list. 

On the other side, the 404 comes when accesing the add url of the form (maybe another problem).

**Comment by linuxrrze** [comment]
Same here:

```
angular.min.js?v=3c887df…:107 TypeError: $http.post(...).success(...).error(...).fail is not a function
    at b.$scope.addCity (app.js?v=3c887df…:266)
    at fn (eval at compile (angular.min.js?v=3c887df…:212), <anonymous>:4:305)
    at f (angular.min.js?v=3c887df…:253)
    at b.$eval (angular.min.js?v=3c887df…:133)
    at b.$apply (angular.min.js?v=3c887df…:133)
    at HTMLInputElement.<anonymous> (angular.min.js?v=3c887df…:254)
    at HTMLInputElement.dispatch (jquery.min.js:3)
    at HTMLInputElement.r.handle (jquery.min.js:3)

angular.min.js?v=3c887df…:93 POST http://XXXXXX/index.php/apps/weather/city/add 404 (Not Found)
```

Environment:
- Nextcloud 11.0.3
- weather: 1.3.5

**Comment by nerzhul** [comment]
I'm working on it, updating to 1.6.2

**Comment by nerzhul** [comment]
Fixed by c6f3df8df289c18d7ec6c25a93d0f6cbcd3663b2

**Comment by spacorum** [comment]
Thanks, nerzhul! 
Excuse me if this question is too obvious but.. how can I get this update now?

**Comment by nerzhul** [comment]
Just wait, i will release a version this weekend
